### ISSUE TITLE
How to use it with MenuItem?

### ISSUE THREAD

**Issue by Asad4429** [mreram/ShowCaseView#6]
Hi, this is really a nice library. but i think there is no way to use this library for MenuItems in ActionBar. kindly tell me some example for that if we can do it. Obviously this should be done without click on menu item (show automatically when activity starts).
Thanks

Same as shown in image
![image](https://user-images.githubusercontent.com/14857273/39806279-ed2d5286-5392-11e8-8f22-3d9fc93555b8.png)

**Comment by EfeBudak** [comment]
Hi @Asad4429 , I also struggled with using the library with a menu item. Here are my findings;
- You can get the view of the menu item by using 'findViewById' method with the id of the menu item. It does not work with this library because of the context of that view is not an activity but a ContextWrapper. Sorry about that :(
- You can create a Button, ImageView, or a TextView and use it as an actionView of the menu item. That works perfectly. Here is a sample;
```
override fun onCreateOptionsMenu(menu: Menu?, inflater: MenuInflater?) {
        super.onCreateOptionsMenu(menu, inflater)
        inflater?.inflate(R.menu.menu_sample, menu)
        menuItem = menu?.findItem(R.id.menu_item)

        val textViewMenu = TextView(context)
        textViewMenu.text = "ADD"
        textViewMenu.setOnClickListener { doSomethingOnClick() }
        menuItem?.actionView = editMenuItemView
    }
```

You can use "menuItem?.actionView" as your target view. (Happy ending. 👍 )
